services:
    boxer:
     build: .
     ports:
       - '80:80'
     container_name: boxercontainer_2
     volumes: 
       - myapps:/var/www/html/
     network_mode:
       bridge       
  
    counter:
       build: /root/Docker_threetier/counter/
       ports:
         - '8080:8080'
       container_name: countercon
       volumes: 
        - myapps2:/var/www/html/
       network_mode:
        bridge

volumes: 
    myapps:         
    myapps2:      
