services:
    boxer:
     build: .
     ports:
       - '82:80'
     container_name: boxer123
     volumes: 
       - myapps:/var/www/html/
     network_mode:
       bridge       
  
    counter:
       build: /root/Docker_threetier/counter/
       ports:
         - '81:80'
       container_name: counter123
       volumes: 
        - myapps2:/var/www/html/
       network_mode:
        bridge

volumes: 
    myapps:         
    myapps2:      
