services:
    boxer:
     build: .
     ports:
       - '80:80'
     container_name: boxercontainer
     volumes: 
       - myapp:/var/www/html/
     network_mode:
       bridge

volumes: 
    myapp: 

counter:
     build: /Docker_threetier/counter/
     ports:
       - '8080:8080'
     container_name: countercontiner
     volumes: 
       - myapp:/var/www/html/
     network_mode:
       bridge

volumes: 
    myapp:         
          
